#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

set -e

case "$1" in
    remove|purge)
        dpkg-trigger update-initramfs
        ;;
esac

#DEBHELPER#

exit 0
