#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

set -e

#DEBHELPER#

case "$1" in
    configure)
        dpkg-trigger update-initramfs
        ;;
esac

exit 0
