#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.

set -e

module_loaded()
{
    grep -q "^$1 " /proc/modules 2>/dev/null
}

case "$1" in
    remove|upgrade|deconfigure)
        if module_loaded iris_vpu; then
            modprobe -r iris_vpu || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
