name: Build Debian Package
description: |
  Builds the debian package represented by this repo at the ref pointed by the debain-ref argument.

on:
  workflow_dispatch:
    inputs:

      debian-ref:
        description: The debian ref to build. For example branch "debian/qcom-next" or tag "debian/1.0.0-1"
        type: string
        required: true
        default: debian/qcom-next

      distro-codename:
        description: The distribution codename to build for. Ex noble, questing, etc
        type: choice
        default: noble
        options:
          - noble
          - questing
          - resolute
          - trixie
          - sid

      abi-checker:
        description: Run the ABI checker or not
        type: boolean
        default: false

permissions:
  contents: read
  packages: read

jobs:
  build:
    uses: qualcomm-linux/qcom-build-utils/.github/workflows/qcom-build-pkg-reusable-workflow.yml@main
    with:
      qcom-build-utils-ref: main
      debian-ref: ${{ inputs.debian-ref }}
      distro-codename: ${{ inputs.distro-codename }}
      run-abi-checker: ${{ inputs.abi-checker }}